services:
  app:
    image: ghcr.io/cupatea/online:latest
    container_name: online
    restart: unless-stopped
    network_mode: host
    volumes:
      - online_data:/rails/storage

volumes:
  online_data:
